Add Odroid board selection
armbian/configng pull request #298
Opened 2024-12-02 19:08 UTC by GeoffClements

# Description

This change provides a new dialog under system that will update or append `board_name=<xu4, xu3, xu3l, hc1>` to `/boot/armbianEnv.txt`. It will also change the `BOARD_NAME` value in `/etc/armbian-release`.

The option to do this will appear only if the board family is `odroidxu4`.

The returns some functionality that was lost in the upgrade to `armbian-configng`.

Issue reference:  None.
Related documentation: None

# Implementation Details

_Provide a detailed description of the implementation. Include the following:_

- [*] Key changes introduced by this PR
A new entry in `config.system.json` and a new file under `tools/modules/system`.

- [*] Justification for the changes
Returns lost functionality

- [*] Confirmation that no new external dependencies or modules have been introduced
Confirmed

# Documentation Summary

- [*] **Metadata Included:**  
  _Did you include the metadata (associative arrays) in the code? Ensure that metadata for modules, jobs, and runtime has been updated appropriately._
The metadata is included, but I'm not sure I got this completely right.

- [ ] **Document Generated:**  
  _Did you generate the updated documentation using `armbian-configng --doc`? Confirm if the command was run to update `README.md` and provide any relevant details._
There are no documentation changes.

# Testing Procedure

_Describe the tests you ran to verify your changes. Provide relevant details about your test configuration._

Manually tested, conditions tested were:
- Correct line added when missing
- Correct line added when already present
- Ok and Cancel actions

# Checklist

- [*] My code follows the style guidelines of this project
- [*] I have performed a self-review of my code
- [*] I have ensured that my changes do not introduce new warnings or errors
- [*] No new external dependencies are included
- [*] Changes have been tested and verified
- [*] I have included necessary metadata in the code, including associative arrays

2024-12-03 18:12 UTC, igorpecovnik requested changes

2024-12-03 18:12 UTC, igorpecovnik commented on tools/modules/system/manage_odroid_board.sh
> +["manage_odroid_board,author"]=""
Put yourself here.

2024-12-03 18:12 UTC, igorpecovnik commented on tools/json/config.system.json
> +                        "manage_odroid_board"
name function 

module_select_xuodroid

2024-12-03 18:12 UTC, igorpecovnik commented on tools/modules/system/manage_odroid_board.sh
> +	local board_list=("Odroid XU4" "Odroid XU3" "Odroid XU3 Lite" "Odroid HC1/HC2")
Keep indentation the same everywhere, similar to template
https://github.com/armbian/configng/blob/main/tools/template/module_software_template.sh

Also in module_options.

2024-12-04 22:53 UTC, igorpecovnik approved these changes

2024-12-04 23:37 UTC, GeoffClements commented
Apologies for the commits and reverts. I didn't realise those commits would appear in the PR, consequently I reverted them.

2024-12-04 23:43 UTC, igorpecovnik commented
No worries. I think we are good to go at my last commit. Everyone had troubles with Git-Fu, if you struggle with this, I will it in the morning.

2024-12-05 06:31 UTC, merged